config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'customers#index'
  resources :plans
  resources :customers do
    resources :trainings
    resources :attendances
  end
  resources :subscriptions
  get 'subscriptions/:id/send_invoice_email', to: 'subscriptions#send_invoice_email', as: 'send_invoice_email'
  get 'subscriptions/:id/print_invoice', to: 'subscriptions#print_invoice', as: 'print_invoice'
  get 'customers/:customer_ids/send_birthday_email', to:'customers#send_birthday_email', as: 'send_birthday_email'
  get 'customers/:id/send_subscription_email', to:'customers#send_subscription_email', as: 'send_subscription_email'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :customer
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :get_customer
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  def index
    @title = "Rutinas de #{@customer.name}"
    respond_to do |format|
      format.html
      format.json { render json: TrainingDatatable.new(params, view_context: view_context, customer: params[:customer_id]) }
    end
  end

  def show
  end

  def new
    @training = @customer.trainings.build
    @title = "Nueva Rutina para #{@customer.name}"
  end

  def create
    @training = @customer.trainings.build(training_params)
    if @training.save
      redirect_to customer_trainings_path(@customer), notice: 'La Rutina se ha creado correctamente'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @training.update(training_params)
      redirect_to customer_trainings_path(@customer), notice: 'La Rutina se ha actualizado correctamente'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @training.destroy
  end

  private

  def get_customer
    @customer = Customer.find(params[:customer_id])
  end

  def set_training
    @training = Training.find((params[:id]))
  end

  def training_params
    params.require(:training).permit(:number, :start, :customer)
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_with(model: [@customer, @training], local: true) do |form| %>
  <div class="card-body">
    <div class="form-group">
      <%= form.label :number, "Número" %>
      <%= form.text_field :number, class: "form-control", :required => true %>
    </div>
    <div class="form-group">
      <%= form.label :start, "Fecha de Inicio" %>
      <%= form.date_field :start, class: "form-control", :required => true %>
    </div>
  </div>

  <div class="card-footer">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/trainings/create.html.erb
<h1>Trainings#create</h1>
<p>Find me in app/views/trainings/create.html.erb</p>

app/views/trainings/destroy.html.erb
<h1>Trainings#destroy</h1>
<p>Find me in app/views/trainings/destroy.html.erb</p>

app/views/trainings/edit.html.erb
<%= render "shared/card_model", form: "form", subtitle: "Detalles de la Rutina" %>

app/views/trainings/index.html.erb
<%= render 'shared/flash' %>
<%= link_to new_customer_training_path, class: "btn btn-primary mb-2" do %>
  <%= icon("fas", "plus", "Nueva Rutina") %>
<% end %>
<div class="table-responsive">
  <table id="trainings-datatable" data-turbo="false" class="table table-striped table-bordered nowrap" data-controller="loadTrainings destroyTraining" data-source="<%= customer_trainings_path(format: :json) %>" style="width: 100%">
    <thead>
    <tr class="table-active">
      <th data-priority="0"></th>
      <th data-priority="1">Número</th>
      <th data-priority="3">Fecha de Inicio</th>
      <th data-priority="2">Acciones</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/trainings/new.html.erb
<%= render "shared/card_model", form: "form", subtitle:  "Detalles de la Rutina"%>

app/views/trainings/show.html.erb
<h1>Trainings#show</h1>
<p>Find me in app/views/trainings/show.html.erb</p>

app/views/trainings/update.html.erb
<h1>Trainings#update</h1>
<p>Find me in app/views/trainings/update.html.erb</p>