config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'customers#index'
  resources :plans
  resources :customers do
    resources :trainings
    resources :attendances
  end
  resources :subscriptions
  get 'subscriptions/:id/send_invoice_email', to: 'subscriptions#send_invoice_email', as: 'send_invoice_email'
  get 'subscriptions/:id/print_invoice', to: 'subscriptions#print_invoice', as: 'print_invoice'
  get 'customers/:customer_ids/send_birthday_email', to:'customers#send_birthday_email', as: 'send_birthday_email'
  get 'customers/:id/send_subscription_email', to:'customers#send_subscription_email', as: 'send_subscription_email'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :customer
  belongs_to :plan

  def is_active
    (self.start..self.end) === DateTime.current.to_date
  end

  def self.day_total
    time_range = Time.now.midnight..(Time.now.midnight + 1.day)
    data = Subscription.joins(:plan).where('subscriptions.created_at' => time_range).group('date(subscriptions.created_at)').select('date(subscriptions.created_at) AS dia, sum(plans.price) AS total')
    if data.exists?
      data.first.total
    else
      0
    end

  end

  def self.month_total
    time_range = Date.today.beginning_of_month..Date.today.end_of_month
    data = Subscription.joins(:plan).where('subscriptions.created_at' => time_range).group('date(subscriptions.created_at)').select('sum(plans.price) AS total')
    if data.exists?
      total = 0
      data.each do |dia|
        total += dia.total
      end
      total
    else
      0
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  layout "admin", :except => :print_invoice
  before_action :authenticate_user!
  before_action :set_subscription, only: [:show, :edit, :update, :destroy, :send_invoice_email, :print_invoice]

  def index
    @title = "Suscripciones"
    @day_total = Subscription.day_total
    @month_total = Subscription.month_total
    respond_to do |format|
      format.html
      format.json { render json: SubscriptionDatatable.new(params, view_context: view_context) }
    end
  end

  def show
    @iframe = print_invoice_path(@subscription)
  end

  def new
    @subscription = Subscription.new
    @title = "Nueva Suscripción"
  end

  def create
    @customer = Customer.find(params[:subscription][:customer_id])
    if @customer.subscription_status
      start_sub = @customer.subscriptions.last.end + 1.days
    else
      start_sub = DateTime.current.to_date
    end
    @subscription = Subscription.create(subscription_params)
    @subscription.start = start_sub
    @subscription.end = params[:subscription][:end]
    if @subscription.save
      SubscriptionMailer.with(subscription: @subscription).invoice.deliver_later
      redirect_to subscriptions_path, notice: 'La Suscripción se ha creado correctamente'
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @title = "Editar Suscripción"
  end

  def update
    if @subscription.update(subscription_params)
      redirect_to subscriptions_path, notice: 'La Suscripción se ha actualizado correctamente'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @subscription.destroy
  end

  def send_invoice_email
    SubscriptionMailer.with(subscription: @subscription).invoice.deliver_later
  end

  def print_invoice
  end

  private

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  def subscription_params
    params.require(:subscription).permit(:customer_id, :plan_id, :end)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with model: @subscription do |form| %>
  <div class="card-body">
    <div class="form-group">
      <%= form.label :customer_id, "Cliente" %>
      <%= form.collection_select(:customer_id, Customer.all, :id, :info, { include_blank: 'Seleccione un cliente' }, { class: "form-control select2", required: true }) %>
    </div>
    <div class="form-group">
      <%= form.label :plan_id, "Plan" %>
      <%= form.collection_select(:plan_id, Plan.all, :id, :name, { include_blank: 'Seleccione un plan' }, { class: "form-control select2", required: true }) %>
    </div>
    <div class="form-group">
      <%= form.label :end, "Fin de suscripción" %>
      <%= form.date_field :end, class: "form-control", :required => true %>
    </div>
  </div>

  <div class="card-footer">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/destroy.html.erb
<h1>Subscriptions#destroy</h1>
<p>Find me in app/views/subscriptions/destroy.html.erb</p>

app/views/subscriptions/edit.html.erb
<h1>Subscriptions#edit</h1>
<p>Find me in app/views/subscriptions/edit.html.erb</p>

app/views/subscriptions/index.html.erb
<%= render 'shared/flash' %>
<%= link_to new_subscription_path, class: "btn btn-primary mb-2" do %>
  <%= icon("fas", "plus", "Nueva Suscripción") %>
<% end %>
<div class="table-responsive">
  <table id="subscriptions-datatable" data-turbo="false" class="table table-striped table-bordered nowrap" data-controller="loadSubscriptions destroySubscription" data-source="<%= subscriptions_path(format: :json) %>" style="width: 100%">
    <thead>
    <tr class="table-active">
      <th data-priority="0"></th>
      <th data-priority="1">#</th>
      <th data-priority="5">¿Activa?</th>
      <th data-priority="2">Cliente</th>
      <th data-priority="4">Plan</th>
      <th data-priority="6">Inicio</th>
      <th data-priority="7">Fin</th>
      <th data-priority="3">Acciones</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>
<p class="text-bold">Hoy: $<%= @day_total %></p>
<p class="text-bold">Mes: $<%= @month_total %></p>

app/views/subscriptions/new.html.erb
<%= render "shared/card_model", form: "form", subtitle:  "Detalles de la Suscripción"%>

app/views/subscriptions/print_invoice.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title></title>

  <style>
      td {
          font-size: 24px;
      }

      .invoice-box {
          max-width: 800px;
          margin: auto;
          padding: 30px;
          border: 1px solid #eee;
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
          font-size: 16px;
          line-height: 24px;
          font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
          color: #555;
      }

      .invoice-box table {
          width: 100%;
          line-height: inherit;
          text-align: left;
      }

      .invoice-box table td {
          padding: 5px;
          vertical-align: top;
      }

      .invoice-box table tr td:nth-child(2) {
          text-align: right;
      }

      .invoice-box table tr.top table td {
          padding-bottom: 20px;
      }

      .invoice-box table tr.top table td.title {
          font-size: 45px;
          line-height: 45px;
          color: #333;
      }

      .invoice-box table tr.information table td {
          padding-bottom: 40px;
      }

      .invoice-box table tr.heading td {
          background: #eee;
          border-bottom: 1px solid #ddd;
          font-weight: bold;
      }

      .invoice-box table tr.details td {
          padding-bottom: 20px;
      }

      .invoice-box table tr.item td {
          border-bottom: 1px solid #eee;
      }

      .invoice-box table tr.item.last td {
          border-bottom: none;
      }

      .invoice-box table tr.total td:nth-child(2) {
          border-top: 2px solid #eee;
          font-weight: bold;
      }

      @media only screen and (max-width: 600px) {
          .invoice-box table tr.top table td {
              width: 100%;
              display: block;
              text-align: center;
          }

          .invoice-box table tr.information table td {
              width: 100%;
              display: block;
              text-align: center;
          }
      }

      /** RTL **/
      .invoice-box.rtl {
          direction: rtl;
          font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
      }

      .invoice-box.rtl table {
          text-align: right;
      }

      .invoice-box.rtl table tr td:nth-child(2) {
          text-align: left;
      }
  </style>
</head>

<body>
<div class="invoice-box">
  <table cellpadding="0" cellspacing="0">
    <tr class="top">
      <td colspan="2">
        <table>
          <tr>
            <td class="title">
<!--              <img src="#" style="width: 100%; max-width: 300px" />-->
            </td>

            <td>
              Factura #: <%= @subscription.id %><br />
              Fecha: <%= @subscription.created_at.strftime('%d/%m/%Y') %><br />
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <tr class="information">
      <td colspan="2">
        <table>
          <tr>
            <td>
              GYM FUERZA Y SALUD<br />
              Calle 30 #23-34 Girón<br />
              6465189
            </td>

            <td>
              <%= @subscription.customer.name %><br />
              <%= @subscription.customer.created_at.strftime('%d/%m/%Y') %><br />
              <%= @subscription.customer.email %>
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <tr class="heading">
      <td>Suscripción</td>

      <td>Detalle</td>
    </tr>

    <tr class="details">
      <td>Plan</td>

      <td><%= @subscription.plan.name %></td>
    </tr>

    <tr class="details">
      <td>Fecha de inicio</td>

      <td><%= @subscription.start.strftime('%d/%m/%Y') %></td>
    </tr>

    <tr class="details">
      <td>Fecha de fin</td>

      <td><%= @subscription.end.strftime('%d/%m/%Y') %></td>
    </tr>

    <tr class="heading">
      <td>Plan</td>

      <td>Precio</td>
    </tr>

    <tr class="item last">
      <td><%= @subscription.plan.name %></td>

      <td>$<%= @subscription.plan.price %></td>
    </tr>

    <tr class="total">
      <td></td>

      <td>Total: $<%= @subscription.plan.price %></td>
    </tr>
  </table>
</div>
</body>
</html>

app/views/subscriptions/send_invoice_email.html.erb
<div bgcolor="#f6f6f6" style="color: #333; height: 100%; width: 100%;" height="100%" width="100%">
  <table bgcolor="#f6f6f6" cellspacing="0" style="border-collapse: collapse; padding: 40px; width: 100%;" width="100%">
    <tbody>
    <tr>
      <td width="5px" style="padding: 0;"></td>
      <td style="clear: both; display: block; margin: 0 auto; max-width: 600px; padding: 10px 0;">
        <table width="100%" cellspacing="0" style="border-collapse: collapse;">
          <tbody>
          <tr>
            <td style="padding: 0;">
              <%= image_tag "gym_invoice.jpg", style: "height: 50px; max-width: 100%; width: 157px;" %>
            </td>
            <td style="color: #999; font-size: 16px; font-weight: bold; padding: 0; text-align: right;" align="right">
              GYM FUERZA Y SALUD<br/>
              Factura #<%= @subscription.id %><br/>
              <%= DateTime.current.to_date.strftime('%d/%m/%Y') %>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
      <td width="5px" style="padding: 0;"></td>
    </tr>

    <tr>
      <td width="5px" style="padding: 0;"></td>
      <td bgcolor="#FFFFFF" style="border: 1px solid #000; clear: both; display: block; margin: 0 auto; max-width: 600px; padding: 0;">
        <table width="100%" style="background: #f9f9f9; border-bottom: 1px solid #eee; border-collapse: collapse; color: #999;">
          <tbody>
          <tr>
            <td width="50%" style="padding: 20px;">
              <strong style="color: #333; font-size: 24px;">FACTURA #<%= @subscription.id %></strong></td>
            <td align="right" width="50%" style="padding: 20px;"><%= @subscription.customer.name %></td>
          </tr>
          </tbody>
        </table>
      </td>
      <td style="padding: 0;"></td>
      <td width="5px" style="padding: 0;"></td>
    </tr>
    <tr>
      <td width="5px" style="padding: 0;"></td>
      <td style="border: 1px solid #000; border-top: 0; clear: both; display: block; margin: 0 auto; max-width: 600px; padding: 0;">
        <table cellspacing="0" style="border-collapse: collapse; border-left: 1px solid #000; margin: 0 auto; max-width: 600px;">
          <tbody>
          <tr>
            <td valign="top" style="padding: 20px;">
              <h3
                style="
                border-bottom: 1px solid #000;
                  color: #000;
                  font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif;
                  font-size: 18px;
                  font-weight: bold;
                  line-height: 1.2;
                  margin: 0;
                  margin-bottom: 15px;
                  padding-bottom: 5px;
                "
              >
                Resumen
              </h3>
              <table cellspacing="0" style="border-collapse: collapse; margin-bottom: 40px;">
                <tbody>
                <tr>
                  <td style="padding: 5px 0;">Plan</td>
                  <td align="right" style="padding: 5px 0;"><%= @subscription.plan.name %></td>
                </tr>
                <tr>
                  <td style="padding: 5px 0;">Precio</td>
                  <td align="right" style="padding: 5px 0;"><%= @subscription.plan.price %></td>
                </tr>
                <tr>
                  <td style="padding: 5px 0;">Fecha de inicio</td>
                  <td align="right" style="padding: 5px 0;"><%= @subscription.start.strftime('%d/%m/%Y') %></td>
                </tr>
                <tr>
                <tr>
                  <td style="padding: 5px 0;">Fecha de fin</td>
                  <td align="right" style="padding: 5px 0;"><%= @subscription.end.strftime('%d/%m/%Y') %></td>
                </tr>
                <tr>
                <tr>
                  <td style="border-bottom: 2px solid #000; border-top: 2px solid #000; font-weight: bold; padding: 5px 0;">Total
                  </td>
                  <td align="right" style="border-bottom: 2px solid #000; border-top: 2px solid #000; font-weight: bold; padding: 5px 0;">$<%= @subscription.plan.price %></td>
                </tr>
                <tr>
                <tr>
                  <td style="padding: 5px 0;">GYM FUERZA Y SALUD - 39 Años de experiencia. <br> <i>¡Gracias por su compra!</i></td>
                  <td align="right" style="padding: 5px 0;"></td>
                </tr>
                <tr>
                </tbody>
              </table>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
      <td width="5px" style="padding: 0;"></td>
    </tr>
    </tbody>
  </table>
</div>

app/views/subscriptions/send_invoice_email.text.erb
Hola <%= @subscription.customer.name %>

A continuación se adjunta la información de tu compra:

Fecha: <%= @subscription.created_at.strftime('%d/%m/%Y') %>
Factura # <%= @subscription.id %>

Gracias por comprar tu plan <%= @subscription.plan.name %> con un costo de $<%= @subscription.plan.price %> con nosotros.
En GYM Fuerza Y Salud contamos con 39 años de experiencia y estamos felices de poder ayudarte en este proceso de tener en una vida más saludable.

Detalles de tu plan:
Fecha de inicio: <%= @subscription.start %>
Fecha de fin: <%= @subscription.end %>

Una vez más gracias por elegirnos y nos vemos en el entrenamiento.

app/views/subscriptions/show.html.erb
<%= link_to send_invoice_email_path(@subscription), class: "btn btn-primary" do %>
  <%= icon("fas", "envelope-square", "Enviar factura al correo") %>
<% end %>
<iframe src="<%= @iframe %>" style="display:none;" name="frame"></iframe>
<button type="button" class="btn btn-info" onclick="frames['frame'].print()"><i class="fas fa-print"></i> Imprimir
</button>
<div bgcolor="#f6f6f6" style="color: #333; height: 100%; width: 100%;" height="100%" width="100%">
  <table bgcolor="#f6f6f6" cellspacing="0" style="border-collapse: collapse; padding: 40px; width: 100%;" width="100%">
    <tbody>
    <tr>
      <td width="5px" style="padding: 0;"></td>
      <td style="clear: both; display: block; margin: 0 auto; max-width: 600px; padding: 10px 0;">
        <table width="100%" cellspacing="0" style="border-collapse: collapse;">
          <tbody>
          <tr>
            <td style="padding: 0;">
              <%= image_tag "gym_invoice.jpg", style: "height: 50px; max-width: 100%; width: 157px;" %>
            </td>
            <td style="color: #999; font-size: 16px; font-weight: bold; padding: 0; text-align: right;" align="right">
              GYM FUERZA Y SALUD<br/>
              Factura #<%= @subscription.id %><br/>
              <%= DateTime.current.to_date.strftime('%d/%m/%Y') %>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
      <td width="5px" style="padding: 0;"></td>
    </tr>

    <tr>
      <td width="5px" style="padding: 0;"></td>
      <td bgcolor="#FFFFFF" style="border: 1px solid #000; clear: both; display: block; margin: 0 auto; max-width: 600px; padding: 0;">
        <table width="100%" style="background: #f9f9f9; border-bottom: 1px solid #eee; border-collapse: collapse; color: #999;">
          <tbody>
          <tr>
            <td width="50%" style="padding: 20px;">
              <strong style="color: #333; font-size: 24px;">FACTURA #<%= @subscription.id %></strong></td>
            <td align="right" width="50%" style="padding: 20px;"><%= @subscription.customer.name %></td>
          </tr>
          </tbody>
        </table>
      </td>
      <td style="padding: 0;"></td>
      <td width="5px" style="padding: 0;"></td>
    </tr>
    <tr>
      <td width="5px" style="padding: 0;"></td>
      <td style="border: 1px solid #000; border-top: 0; clear: both; display: block; margin: 0 auto; max-width: 600px; padding: 0;">
        <table cellspacing="0" style="border-collapse: collapse; border-left: 1px solid #000; margin: 0 auto; max-width: 600px;">
          <tbody>
          <tr>
            <td valign="top" style="padding: 20px;">
              <h3
                style="
                border-bottom: 1px solid #000;
                  color: #000;
                  font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif;
                  font-size: 18px;
                  font-weight: bold;
                  line-height: 1.2;
                  margin: 0;
                  margin-bottom: 15px;
                  padding-bottom: 5px;
                "
              >
                Resumen
              </h3>
              <table cellspacing="0" style="border-collapse: collapse; margin-bottom: 40px;">
                <tbody>
                <tr>
                  <td style="padding: 5px 0;">Plan</td>
                  <td align="right" style="padding: 5px 0;"><%= @subscription.plan.name %></td>
                </tr>
                <tr>
                  <td style="padding: 5px 0;">Precio</td>
                  <td align="right" style="padding: 5px 0;"><%= @subscription.plan.price %></td>
                </tr>
                <tr>
                  <td style="padding: 5px 0;">Fecha de inicio</td>
                  <td align="right" style="padding: 5px 0;"><%= @subscription.start.strftime('%d/%m/%Y') %></td>
                </tr>
                <tr>
                <tr>
                  <td style="padding: 5px 0;">Fecha de fin</td>
                  <td align="right" style="padding: 5px 0;"><%= @subscription.end.strftime('%d/%m/%Y') %></td>
                </tr>
                <tr>
                <tr>
                  <td style="border-bottom: 2px solid #000; border-top: 2px solid #000; font-weight: bold; padding: 5px 0;">Total
                  </td>
                  <td align="right" style="border-bottom: 2px solid #000; border-top: 2px solid #000; font-weight: bold; padding: 5px 0;">$<%= @subscription.plan.price %></td>
                </tr>
                <tr>
                <tr>
                  <td style="padding: 5px 0;">GYM FUERZA Y SALUD - 39 Años de experiencia. <br>
                    <i>¡Gracias por su compra!</i></td>
                  <td align="right" style="padding: 5px 0;"></td>
                </tr>
                <tr>
                </tbody>
              </table>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
      <td width="5px" style="padding: 0;"></td>
    </tr>
    </tbody>
  </table>
</div>

app/views/subscriptions/update.html.erb
<h1>Subscriptions#update</h1>
<p>Find me in app/views/subscriptions/update.html.erb</p>