config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'customers#index'
  resources :plans
  resources :customers do
    resources :trainings
    resources :attendances
  end
  resources :subscriptions
  get 'subscriptions/:id/send_invoice_email', to: 'subscriptions#send_invoice_email', as: 'send_invoice_email'
  get 'subscriptions/:id/print_invoice', to: 'subscriptions#print_invoice', as: 'print_invoice'
  get 'customers/:customer_ids/send_birthday_email', to:'customers#send_birthday_email', as: 'send_birthday_email'
  get 'customers/:id/send_subscription_email', to:'customers#send_subscription_email', as: 'send_subscription_email'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :subscriptions
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  def index
    @title = "Planes"
    respond_to do |format|
      format.html
      format.json { render json: PlanDatatable.new(params, view_context: view_context) }
    end
  end

  def show
  end

  def new
    @plan = Plan.new
    @title = "Nuevo Plan"
  end

  def create
    if Plan.create(plan_params)
      redirect_to plans_path, notice: 'El Plan se ha creado correctamente'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @title = "Editar Plan"
  end

  def update
    if @plan.update(plan_params)
      redirect_to plans_path, notice: 'El Plan se ha actualizado correctamente'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @plan.destroy
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:name, :price)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with model: @plan do |form| %>
  <div class="card-body">
    <div class="form-group">
      <%= form.label :name, "Nombre" %>
      <%= form.text_field :name, class: "form-control", :required => true %>
    </div>
    <div class="form-group">
      <%= form.label :price, "Precio" %>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text"><i class="fas fa-dollar-sign"></i></span>
        </div>
        <%= form.text_field :price, class: "form-control", :required => true %>
      </div>
    </div>
  </div>

  <div class="card-footer">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/plans/create.html.erb
<h1>Plans#create</h1>
<p>Find me in app/views/plans/create.html.erb</p>

app/views/plans/destroy.html.erb
<h1>Plans#destroy</h1>
<p>Find me in app/views/plans/destroy.html.erb</p>

app/views/plans/edit.html.erb
<%= render "shared/card_model", form: "form", subtitle: "Detalles de la Categoría" %>

app/views/plans/index.html.erb
<%= render 'shared/flash' %>
<%= link_to new_plan_path, class: "btn btn-primary mb-2" do %>
  <%= icon("fas", "plus", "Nuevo Plan") %>
<% end %>
<div class="table-responsive">
  <table id="plans-datatable" data-turbo="false" class="table table-striped table-bordered nowrap" data-controller="loadPlans destroyPlan" data-source="<%= plans_path(format: :json) %>" style="width: 100%">
    <thead>
    <tr class="table-active">
      <th data-priority="0"></th>
      <th data-priority="1">Nombre</th>
      <th data-priority="3">Precio</th>
      <th data-priority="2">Acciones</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/plans/new.html.erb
<%= render "shared/card_model", form: "form", subtitle:  "Detalles del Plan"%>

app/views/plans/show.html.erb
<h1>Plans#show</h1>
<p>Find me in app/views/plans/show.html.erb</p>

app/views/plans/update.html.erb
<h1>Plans#update</h1>
<p>Find me in app/views/plans/update.html.erb</p>