config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'customers#index'
  resources :plans
  resources :customers do
    resources :trainings
    resources :attendances
  end
  resources :subscriptions
  get 'subscriptions/:id/send_invoice_email', to: 'subscriptions#send_invoice_email', as: 'send_invoice_email'
  get 'subscriptions/:id/print_invoice', to: 'subscriptions#print_invoice', as: 'print_invoice'
  get 'customers/:customer_ids/send_birthday_email', to:'customers#send_birthday_email', as: 'send_birthday_email'
  get 'customers/:id/send_subscription_email', to:'customers#send_subscription_email', as: 'send_subscription_email'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GYM Fuerza Y Salud</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-track-turbo": "reload", defer: true %>
</head>

<body class="hold-transition sidebar-mini layout-fixed">

<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item h2 font-weight-bold text-maroon">
        GYM FUERZA Y SALUD
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
          <i class="fas fa-birthday-cake"></i>
          <span class="badge badge-success navbar-badge text-bold"><%= Customer.birthday.count %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">
          <span class="dropdown-item dropdown-header text-primary text-bold">Cumpleañeros de hoy: (<%= Customer.birthday.count %>)</span>
          <% Customer.birthday.each do |customer| %>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
              <i class="far fa-smile-beam mr-2"></i> <%= customer.name %>
              <span class="float-right text-muted text-sm"><%= customer.age %></span>
            </a>
          <% end %>
          <div class="dropdown-divider"></div>
          <% if Customer.birthday.count > 0 %>
            <%= link_to send_birthday_email_path(Customer.birthday.pluck(:id).join("-")), class: "dropdown-item dropdown-footer bg-success" do %>
              <%= icon("fas", "birthday-cake", "Enviar felicitación al correo") %>
            <% end %>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
          <i class="fas fa-hourglass-half"></i>
          <span class="badge badge-warning navbar-badge text-bold"><%= Customer.subscription_reminder.count %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">
          <span class="dropdown-item dropdown-header text-orange text-bold">Suscripciones próximas a vencer: (<%= Customer.subscription_reminder.count %>)</span>
          <% Customer.subscription_reminder.each do |customer| %>
            <div href="#" class="dropdown-item">
              <div class="media">
                <i class="fas fa-user-circle"></i>
                <div class="media-body ml-2">
                  <h3 class="dropdown-item-title">
                    <%= customer.name %>
                    <%= link_to send_subscription_email_path(customer.id), class: "d-inline float-right text-sm text-orange" do %>
                      <%= icon("fas", "envelope") %>
                    <% end %>
                  </h3>
                  <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> <%= customer.subscriptions.last.end.strftime('%d/%m/%Y') %></p>
                </div>
              </div>
            </div>
            <div class="dropdown-divider"></div>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
          <i class="far fa-bell"></i>
          <span class="badge badge-danger navbar-badge text-bold"><%= Customer.expired_subscription.count %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">
          <span class="dropdown-item dropdown-header text-danger text-bold">Suscripciones que vencen hoy: (<%= Customer.expired_subscription.count %>)</span>
          <% Customer.expired_subscription.each do |customer| %>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
              <i class="fas fa-user-clock mr-2"></i> <%= customer.name %>
              <span class="float-right text-muted text-sm"><%= customer.subscriptions.count %></span>
            </a>
          <% end %>
        </div>
      </li>

    </ul>
  </nav>  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <%= image_tag "gym.jpg", class: "brand-image img-circle elevation-3" %>
      <span class="brand-text font-weight-light">ADMINISTRACIÓN</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <%= image_tag "user.png", class: "img-circle elevation-2" %>
        </div>
        <div class="info">
          <a href="#" class="d-block"><%= current_user.name %></a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <%= link_to customers_path, class: "nav-link" do %>
              <i class="nav-icon fas fa-users"></i>
              <p>
                Clientes
              </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to subscriptions_path, class: "nav-link" do %>
              <i class="nav-icon fas fa-money-check-alt"></i>
              <p>
                Suscripciones
              </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to plans_path, class: "nav-link" do %>
              <i class="nav-icon fas fa-tags"></i>
              <p>
                Planes
              </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, class: "nav-link", :method => :delete do %>
              <i class="nav-icon fas fa-sign-out"></i>
              <p>
                Salir
              </p>
            <% end %>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <%= content_tag "h1", @title %>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <div class="container-fluid">
        <%= yield %>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Versión</b> 1.0.0
    </div>
    <strong>Copyright &copy; <%= Date.today.year %> <a href="#">Kevin Rueda</a>.</strong> Todos los derechos reservados.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
<%= yield :page_scripts %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaGym</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-track-turbo": "true", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>